services:
  _defaults:
    autowire: true

  Domain\Administration\Company\Handler\:
    resource: '../../src/Domain/Administration/Company/Handler/*'
    tags:
      - { name: messenger.message_handler, bus: command.bus }
