services:
  _defaults:
    autowire: true

  Administration\Domain\Company\Handler\:
    resource: '../../src/Administration/Domain/Company/Handler/*'
    tags:
      - { name: messenger.message_handler, bus: command.bus }
