services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Infrastructure\Administration\Company\Controller\:
    resource: '%kernel.project_dir%/src/Infrastructure/Administration/Company/Controller'
    tags: [ 'controller.service_arguments' ]

  Infrastructure\Persistence\DoctrineOrm\Repositories\:
    resource: '%kernel.project_dir%/src/Infrastructure/Persistence/DoctrineOrm/Repositories/*'
    lazy: true

  Infrastructure\Controllers\:
    resource: '%kernel.project_dir%/src/Infrastructure/Controllers'
    tags: [ 'controller.service_arguments' ]
