imports:
  - { resource: application.yaml }
  - { resource: domain.yaml }
  - { resource: infrastructure.yaml }
  - { resource: inventory.yaml }
  - { resource: administration.yaml }
  - { resource: command-handlers.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
