<?php

namespace AppBundle\Form;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:17.
 */
class RegistrationTypeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RegistrationType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RegistrationType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Form\RegistrationType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Form\RegistrationType::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Form\RegistrationType::getBlockPrefix
     * @todo   Implement testGetBlockPrefix().
     */
    public function testGetBlockPrefix() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Form\RegistrationType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
