services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Administration\Domain\:
    resource: '../../src/Administration/Domain'
    exclude: '../../src/Administration/Domain/**/{Model,Exception}/*'

  Administration\Infrastructure\Company\Controller\:
    resource: '%kernel.project_dir%/src/Administration/Infrastructure/Company/Controller'
    tags: [ 'controller.service_arguments' ]

  Administration\Infrastructure\Settings\Controller\:
    resource: '%kernel.project_dir%/src/Administration/Infrastructure/Settings/Controller'
    tags: [ 'controller.service_arguments' ]

  Administration\Infrastructure\User\Controller\:
    resource: '%kernel.project_dir%/src/Administration/Infrastructure/User/Controller'
    tags: [ 'controller.service_arguments' ]

  Administration\Infrastructure\Supplier\Controller\:
    resource: '%kernel.project_dir%/src/Administration/Infrastructure/Supplier/Controller'
    tags: [ 'controller.service_arguments' ]

  Administration\Infrastructure\Persistence\DoctrineOrm\Repositories\:
    resource: '%kernel.project_dir%/src/Administration/Infrastructure/Persistence/DoctrineOrm/Repositories/*'
    lazy: true

  Administration\Infrastructure\Finders\DoctrineOrm\:
    resource: '%kernel.project_dir%/src/Administration/Infrastructure/Finders/DoctrineOrm/*'
    lazy: true

  Administration\Infrastructure\:
    lazy: true
    resource: '%kernel.project_dir%/src/Administration/Infrastructure/*'
    exclude: '%kernel.project_dir%/src/Administration/Infrastructure/{DoctrineMigrations,Kernel.php,**/Controller}'

  serializer_handler.company:
    class: Administration\Infrastructure\Company\Serializer\Handler\CompanyHandler
    tags:
      - { name: jms_serializer.subscribing_handler }

  serializer_handler.supplier:
    class: Administration\Infrastructure\Supplier\Serializer\Handler\SupplierHandler
    tags:
      - { name: jms_serializer.subscribing_handler }
