services:
  _defaults:
    autowire: true

  Administration\Domain\Settings\Handler\:
    resource: '../../src/Administration/Domain/Settings/Handler/*'
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  Administration\Domain\Supplier\Handler\:
    resource: '../../src/Administration/Domain/Supplier/Handler/*'
    tags:
      - { name: messenger.message_handler, bus: command.bus }
