imports:
  - { resource: inventory.yaml }
  - { resource: administration.yaml }
  - { resource: command-handlers.yaml }
  - { resource: query-handler.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
