doctrine:
  dbal:
    # configure these for your database server
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
    driver: 'pdo_mysql'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Domain\Articl\Modele:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Resources/doctrine/Article'
        prefix: 'Domain\Article\Model'
      Domain\Supplier\Model:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Resources/doctrine/Supplier'
        prefix: 'Domain\Supplier\Model'
