imports:
    - { resource: easyadmin/ }

easy_admin:
    design:
        assets:
            css:
                - 'build/app.css'
        form_theme: 
            - 'horizontal'
            - 'easy_admin/bootstrap_3_horizontal_layout.html.twig'

    site_name: <i class='icon-GLSR'></i> | Admin
    translation_domain: messages

    list:
        actions:
            - { name: 'show', icon: 'search', title: 'Show', label: false }
            - { name: 'edit', icon: 'pencil', title: 'Edit', label: false }
            - { name: 'delete', icon: 'times', title: 'Delete', label: false }

