imports:
    - { resource: easyadmin/ }

easy_admin:
    design:
        brand_color: '#0a50a1'
        assets:
            css:
                - 'build/app.css'
                # - 'bundles/easyadmin/bootstrap-all.css'
            # js:
                # - 'bundles/easyadmin/bootstrap-all.js'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'

    site_name: <i class='icon-GLSR'></i> | Admin
    translation_domain: messages

    list:
        actions:
            - { name: 'show', icon: 'search', title: 'Show', label: false }
            - { name: 'edit', icon: 'pencil', title: 'Edit', label: false }
            - { name: 'delete', icon: 'times', title: 'Delete', label: false }
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y - H:i:s'
