# FOS_User Configuration
fos_user:
    db_driver:       orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:   main
    user_class:      App\Entity\Staff\User
    group:
        group_class: App\Entity\Staff\Group
        form:
            type:    app_user_group
    registration:
        form:
            type: App\Form\RegistrationType
            # if you are using Symfony < 2.8 you should use the type name instead
            # type:    app_user_registration
    from_email:
        address: "noreply@yourcompany.com"
        sender_name: "No Reply"
