security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            # if you're using multiple entity managers
            # manager_name: customer

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            # activate different ways to authenticate
            
            http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
            # https://symfony.com/doc/current/security/form_login_setup.html

            logout: #      true
                path: /logout
                target: /login
            anonymous:    true

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_USER]
        ROLE_USER:        ROLE_USER

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
