# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            sluggable: true
            uploadable: true
            tree: true
            # See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
