twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_theme:
        # resources:
        - LexikFormFilterBundle/Form/form_div_layout.html.twig
        - Form/tel_bootstrap.html.twig
