image: php:5.6

before_script:
    # Install git, the php image doesn't have installed
    - apt-get update -yqq
    - apt-get install git -yqq
    # Install mysql driver
    - docker-php-ext-install pdo_mysql
    # Install composer
    - curl -sS https://getcomposer.org/installer | php
    # Install all project dependencies
    - php composer.phar install

services:
    - mysql

stages:
    - build
    - deploy

build:app:
    script:
        - curl -s https://getcomposer.org/installer | php
        - php composer.phar install
        - rm -rf app/cache/*
        - chmod -R 777 app/cache/ app/logs/
    only:
        - test
