build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths:
        - 'src/*'
    excluded_paths:
        - tests/*
        - Migrations/*
    dependency_paths:
        - config/packages/misd_phone_number.yaml # misd-phone-number for Doctrine
