version: '3.7'

services:

  #APP
  nginx:
    image: library/nginx:1.18
    tty: true
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_PATH}:${APP_CONTAINER_PATH}
    links:
      - php
    ports:
      - ${APP_PORT}:80

  php:
    build:
      context: ./.docker/php
      args:
        - PHP_VERSION=${PHP_VERSION}
    tty: true
    user: ${APP_USER_ID}:${APP_GROUP_ID}
    volumes:
      - ./.docker/php/conf/php-fpm.conf:/etc/php-fpm.d/php-fpm.conf:ro
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/conf.d/100-php.ini:ro
      - ${APP_PATH}:${APP_CONTAINER_PATH}
    links:
      - mariadb

  client:
    image: library/node:14.15
    tty: true
    working_dir: ${APP_CONTAINER_PATH}/client
    user: ${APP_USER_ID}:${APP_GROUP_ID}
    command: yarn run start
    volumes:
      - ${APP_PATH}:${APP_CONTAINER_PATH}

  mariadb:
    image: library/mariadb:10.1.47
    tty: true
    command: mysqld --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_USER_ID: ${APP_USER_ID}
      APP_GROUP_ID: ${APP_GROUP_ID}
    working_dir: ${APP_CONTAINER_PATH}
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./.docker/mysql/scripts/reset:/usr/local/bin/reset
      - ./.docker/mysql/scripts/save:/usr/local/bin/save
      - ./.docker/mysql/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ${APP_PATH}:${APP_CONTAINER_PATH}

#    rabbitmq:
#      image: rabbitmq:3.7-management
#      tty: true
#      ports:
#        - ${RABBITMQ_PORT}:15672
#      volumes:
#        - rabbitmq:/var/lib/rabbitmq/mnesia

volumes:
  mariadb: ~
