version: '3.7'

services:

  adminer:
    image: adminer
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ADMINER_DEFAULT_SERVER: mariadb
    links:
      - mariadb:db
    ports:
      - ${ADMINER_PORT}:8080
