doctrine_migrations:
  migrations_paths:
    'Core\Infrastructure\DoctrineMigrations': '%kernel.project_dir%/src/Core/Infrastructure/DoctrineMigrations'
    'Administration\Infrastructure\DoctrineMigrations': '%kernel.project_dir%/src/Administration/Infrastructure/DoctrineMigrations'
