doctrine:
  dbal:
    # configure these for your database server
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
    driver: 'pdo_mysql'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Core\Domain\Model:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Core/Infrastructure/Resources/doctrine/User'
        prefix: 'Core\Domain\Model'

      Administration\Domain\Company\Model:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Administration/Infrastructure/Resources/doctrine/Administration/Company'
        prefix: 'Administration\Domain\Company\Model'
      Administration\Domain\Settings\Model:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Administration/Infrastructure/Resources/doctrine/Administration/Settings'
        prefix: 'Administration\Domain\Settings\Model'

#      Administration\Domain\Article\Model\Article:
#        is_bundle: false
#        type: xml
#        dir: '%kernel.project_dir%/src/Administration/Infrastructure/Resources/doctrine/Article'
#        prefix: 'Administration\Domain\Article\Model'
#      Administration\Domain\Supplier\Model\Supplier:
#        is_bundle: false
#        type: xml
#        dir: '%kernel.project_dir%/src/Administration/Infrastructure/Resources/doctrine/Supplier'
#        prefix: 'Administration\Domain\Supplier\Model'
