<?php

namespace AppBundle\Menu;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:19.
 */
class MenuBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MenuBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MenuBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Menu\MenuBuilder::buildMainMenu
     * @todo   Implement testBuildMainMenu().
     */
    public function testBuildMainMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Menu\MenuBuilder::buildUserMenu
     * @todo   Implement testBuildUserMenu().
     */
    public function testBuildUserMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
