<?php

namespace AppBundle\Menu;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:19.
 */
class RequestVoterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RequestVoter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RequestVoter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Menu\RequestVoter::matchItem
     * @todo   Implement testMatchItem().
     */
    public function testMatchItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
