<?php

namespace AppBundle\Controller\install;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:22.
 */
class InstallControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var InstallController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new InstallController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Controller\install\InstallController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Controller\install\InstallController::step1Action
     * @todo   Implement testStep1Action().
     */
    public function testStep1Action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Controller\install\InstallController::step2Action
     * @todo   Implement testStep2Action().
     */
    public function testStep2Action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
