<?php

namespace Glsr\GestockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyLogRepository extends EntityRepository
{
}
