<?php

/**
 * InventoryArticles Entité.
 *
 * PHP Version 5
 *
 * @author     Quétier Laurent <lq@dev-int.net>
 * @copyright  2014 Dev-Int GLSR
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 *
 * @version    0.1.0
 *
 * @link       https://github.com/Dev-Int/glsr
 */
namespace Glsr\GestockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * inventoryArticlesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryArticlesRepository extends EntityRepository
{
    /**
     * @param objet Inventory $inventory
     *
     * @return Query result
     */
    public function findByInventory($inventory)
    {
        $qb = $this->createQueryBuilder('ia');

        $qb
          ->where('ia.inventory = :inventory')
          ->setParameter('inventory', $inventory);

        return $qb
        ->getQuery()
        ->getResult();
    }
}
