<?php

namespace Glsr\GestockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubFamilyLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamilyLogRepository extends EntityRepository
{
    public function getFromFamilyLog($id)
    {
        $q = $this->_em->createQuery("SELECT sf FROM GlsrGestockBundle:subFamilyLog sf WHERE sf.familylog = :id");
        $q->setParameter('id', $id);

        return $q->getResult();
    }
}
