imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        glsr_%locale%
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_theme:
#        resources:
        - LexikFormFilterBundle/Form/form_div_layout.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    java: %java_path%
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        # Ajouter cela si vous avez des tables non gérées par Doctrine dans votre bdd
        # (Si vous rencontrez une erreur obscure à propos du type ENUM)
        mapping_types:
            enum: string
        # Fix SensioLabsInsight : A Symfony application should be bootable
        server_version: 5.6
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                regexp: DoctrineExtensions\Query\Mysql\Regexp

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Stof\DoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true
            uploadable: true
            tree: true

# Activation de l'extension Twig intl
services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

# FOS_User Configuration
fos_user:
    db_driver:       orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:   main
    user_class:      AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group
        form:
            type:    app_user_group
    registration:
        form:
            #type: AppBundle\Form\RegistrationType
            # if you are using Symfony < 2.8 you should use the type name instead
            type:    app_user_registration
    from_email:
        address: "noreply@yourcompany.com"
        sender_name: "No Reply"
            
# Knplabs\KnpSnappyBundle
knp_snappy:
    pdf:
        enabled: true
        # if you are using Windows
        binary:  %kernel.root_dir%/Resources/pdf/wkhtmltopdf/windows/bin/wkhtmltopdf.exe
        # if you are using Unix
        # binary:  %kernel.root_dir%/Resources/pdf/wkhtmltopdf/linux/bin/wkhtmltopdf
        options: []
    image:
        enabled: true
        # if you are using Windows
        binary:  %kernel.root_dir%/Resources/pdf/wkhtmltopdf/windows/bin/wkhtmltoimage.exe
        # if you are using Unix
        # binary:  %kernel.root_dir%/Resources/pdf/wkhtmltopdf/linux/bin/wkhtmltoimage
        options: []
        
# JMS_Security_Extra Configuration
jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: true

    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: false

    # Allows you to disable some, or all built-in voters
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           false

    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }

#    util:
#        secure_random:
#            connection: # the doctrine connection name
#            table_name: seed_table
#            seed_provider: # service id of your own seed provider implementation

# Lexik_Form_Filter Configuration
lexik_form_filter:
    force_case_insensitivity: false
    where_method: ~  # null | and | or

# Knp_Paginator Configuration
knp_paginator:
    page_range: %item_per_page%        # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AppBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig 
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
