# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    login_listener:
        class: 'AppBundle\Listener\LoginListener'
        arguments: [ '@fos_user.user_manager' ]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
            - { name: 'kernel.listener', event: 'fos_user.security.implicit_login' }

    menu.voter.request:
        class: 'AppBundle\Menu\RequestVoter'
        arguments: [ '@request_stack' ]
        tags:
            - { name: 'knp_menu.voter' }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
