doctrine:
  orm:
    default_entity_manager: default
    entity_managers:
      default:
        mappings:
          Company:
            type: annotation
            dir: '%kernel.project_dir%/src/Company/Infrastructure/Doctrine/Entity'
            prefix: Company\Infrastructure\Doctrine\Entity
            alias: Company
            is_bundle: false
            mapping: true

framework:
  serializer:
    mapping:
      paths: [ '%kernel.project_dir%/src/Company/Infrastructure/Symfony/Resources/config/serialization' ]

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Company\:
    lazy: true
    resource: '%kernel.project_dir%/src/Company/*'
    exclude: '%kernel.project_dir%/src/Company/{Infrastructure/Symfony,Infrastructure/Doctrine/{Entity,Migrations},Controller}'

  Company\Application\Company\Handler\:
    resource: '../../../../Application/Company/Handler/*'
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  Company\UI\Controller\:
    resource: '%kernel.project_dir%/src/Company/UI/Controller'
    tags: [ 'controller.service_arguments' ]

  Company\Application\Settings\Handler\:
    resource: '%kernel.project_dir%/src/Company/Application/Settings/Handler/*'
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: query.bus }
      - { name: messenger.message_handler, bus: command.bus }
