admin_companies_index:
  path: /
  controller: Administration\Infrastructure\Company\Controller\GetCompaniesController
  methods: GET

admin_companies_post:
  path: /
  controller: Administration\Infrastructure\Company\Controller\PostCompanyController
  methods: POST

admin_company_get:
  path: /new
  controller: Administration\Infrastructure\Company\Controller\GetCompanyController
  methods: GET

admin_company_edit:
  path: /edit/{uuid}
  controller: Administration\Infrastructure\Company\Controller\PutCompanyController
  methods: PUT

admin_company_delete:
  path: /delete/{uuid}
  controller: Administration\Infrastructure\Company\Controller\DeleteCompanyController
  methods: DELETE
