admin_familylogs_index:
  path: /
  controller: Administration\Infrastructure\FamilyLog\Controller\GetFamilyLogsController
  methods: GET

admin_familylogs_post:
  path: /
  controller: Administration\Infrastructure\FamilyLog\Controller\PostFamilyLogController
  methods: POST

admin_familylogs_put:
  path: /{uuid}
  controller: Administration\Infrastructure\FamilyLog\Controller\PutFamilyLogController
  methods: PUT

admin_familylogs_delete:
  path: /{uuid}
  controller: Administration\Infrastructure\FamilyLog\Controller\DeleteFamilyLogController
  methods: DELETE
