admin_company:
  resource: company.yaml
  prefix: /companies

admin_settings:
  resource: settings.yaml
  prefix: /settings

admin_users:
  resource: user.yaml
  prefix: /users

admin_suppliers:
  resource: supplier.yaml
  prefix: /suppliers

admin_familylogs:
  resource: familylog.yaml
  prefix: /familylogs
