admin_settings_index:
  path: /
  controller: Administration\Infrastructure\Settings\Controller\GetSettingsController
  methods: GET

admin_settings_configure:
  path: /
  controller: Administration\Infrastructure\Settings\Controller\PostSettingsController
  methods: POST

admin_settings_edit:
  path: /{uuid}
  controller: Administration\Infrastructure\Settings\Controller\PutSettingsController
  methods: PUT
