admin_user_index:
  path: /
  controller: Administration\Infrastructure\User\Controller\UserIndexController
  methods: GET

admin_user_new:
  path: /new
  controller: Administration\Infrastructure\User\Controller\GetNewUserController
  methods: GET

admin_user_create:
  path: /create
  controller: Administration\Infrastructure\User\Controller\PostUserController
  methods: POST

admin_user_edit:
  path: /edit/{uuid}
  controller: Administration\Infrastructure\User\Controller\GetEditUserController
  methods: GET

admin_user_update:
  path: /update/{uuid}
  controller: Administration\Infrastructure\User\Controller\PutUserController
  methods: PUT

admin_user_delete:
  path: /delete/{uuid}
  controller: Administration\Infrastructure\User\Controller\DeleteUserController
  methods: DELETE
