admin_users_index:
  path: /
  controller: Administration\Infrastructure\User\Controller\GetUsersController
  methods: GET

admin_user_post:
  path: /
  controller: Administration\Infrastructure\User\Controller\PostUserController
  methods: POST

admin_user_update:
  path: /update/{uuid}
  controller: Administration\Infrastructure\User\Controller\PutUserController
  methods: PUT

admin_user_delete:
  path: /delete/{uuid}
  controller: Administration\Infrastructure\User\Controller\DeleteUserController
  methods: DELETE
