admin_users_index:
  path: /
  controller: Administration\Infrastructure\User\Controller\GetUsersController
  methods: GET

admin_users_post:
  path: /
  controller: Administration\Infrastructure\User\Controller\PostUsersController
  methods: POST

admin_user_edit:
  path: /{uuid}
  controller: Administration\Infrastructure\User\Controller\PutUsersController
  methods: PUT

admin_user_delete:
  path: /delete/{uuid}
  controller: Administration\Infrastructure\User\Controller\DeleteUserController
  methods: DELETE
