admin:
  resource: routes/administration/index.yaml
  prefix: /api/administration

inventory:
  resource: routes/inventory/index.yaml
  prefix: /api/inventory

_home:
  path: /api/
  controller: Core\Infrastructure\Controller\DefaultController
  methods: GET

app_login:
  path: /login
  controller: Core\Infrastructure\Controller\SecurityController::login
  methods: GET|POST

app_logout:
  path: /logout
  methods: GET
