admin:
  resource: routes/administration/index.yaml
  prefix: /api/administration

inventory:
  resource: routes/inventory/index.yaml
  prefix: /api/inventory

api_login_check:
  path: /api/login_check
  methods: GET|POST

app_logout:
  path: /logout
  methods: GET
