# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
  - { resource: services/services.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  _instanceof:
    Core\Domain\Protocol\Common\Command\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    Core\Domain\Protocol\Common\Query\QueryHandlerProtocol:
      tags:
        - { name: messenger.message_handler, bus: query.bus }

  Core\Domain\:
    resource: '../src/Core/Domain'
    exclude: '../src/Core/Domain/**/{Model,Exception}/*'

  Core\Infrastructure\:
    lazy: true
    resource: '%kernel.project_dir%/src/Core/Infrastructure/*'
    exclude: '%kernel.project_dir%/src/Core/Infrastructure/{Controller,DoctrineMigrations,Kernel.php}'
