<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Article;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:37.
 */
class ArticleRepositoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ArticleRepository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Article();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\ArticleRepository::getArticles
     * @todo   Implement testGetArticles().
     */
    public function testGetArticles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\ArticleRepository::getArticleFromSupplier
     * @todo   Implement testGetArticleFromSupplier().
     */
    public function testGetArticleFromSupplier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
