<?php

namespace AppBundle\Tests\Entity;

use AppBundle\Entity\Article;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:26.
 */
class ArticleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Article
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Article;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\Article::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setPackaging
     * @todo   Implement testSetPackaging().
     */
    public function testSetPackaging() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getPackaging
     * @todo   Implement testGetPackaging().
     */
    public function testGetPackaging() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setPrice
     * @todo   Implement testSetPrice().
     */
    public function testSetPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getPrice
     * @todo   Implement testGetPrice().
     */
    public function testGetPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setQuantity
     * @todo   Implement testSetQuantity().
     */
    public function testSetQuantity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getQuantity
     * @todo   Implement testGetQuantity().
     */
    public function testGetQuantity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setMinstock
     * @todo   Implement testSetMinstock().
     */
    public function testSetMinstock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getMinstock
     * @todo   Implement testGetMinstock().
     */
    public function testGetMinstock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setSupplier
     * @todo   Implement testSetSupplier().
     */
    public function testSetSupplier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getSupplier
     * @todo   Implement testGetSupplier().
     */
    public function testGetSupplier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setUnitStorage
     * @todo   Implement testSetUnitStorage().
     */
    public function testSetUnitStorage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getUnitStorage
     * @todo   Implement testGetUnitStorage().
     */
    public function testGetUnitStorage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::addZoneStorage
     * @todo   Implement testAddZoneStorage().
     */
    public function testAddZoneStorage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::removeZoneStorage
     * @todo   Implement testRemoveZoneStorage().
     */
    public function testRemoveZoneStorage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getZoneStorages
     * @todo   Implement testGetZoneStorages().
     */
    public function testGetZoneStorages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setFamilyLog
     * @todo   Implement testSetFamilyLog().
     */
    public function testSetFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getFamilyLog
     * @todo   Implement testGetFamilyLog().
     */
    public function testGetFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setSubFamilyLog
     * @todo   Implement testSetSubFamilyLog().
     */
    public function testSetSubFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getSubFamilyLog
     * @todo   Implement testGetSubFamilyLog().
     */
    public function testGetSubFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setActive
     * @todo   Implement testSetActive().
     */
    public function testSetActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::isActive
     * @todo   Implement testIsActive().
     */
    public function testIsActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::setSlug
     * @todo   Implement testSetSlug().
     */
    public function testSetSlug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::getSlug
     * @todo   Implement testGetSlug().
     */
    public function testGetSlug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Article::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
