<?php

namespace AppBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:25.
 */
class CompanyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Company
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Company;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\Company::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Company::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
