<?php

namespace AppBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:24.
 */
class SettingsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Settings
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Settings;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\Settings::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::setInventoryStyle
     * @todo   Implement testSetInventoryStyle().
     */
    public function testSetInventoryStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::getInventoryStyle
     * @todo   Implement testGetInventoryStyle().
     */
    public function testGetInventoryStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::setCalculation
     * @todo   Implement testSetCalculation().
     */
    public function testSetCalculation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::getCalculation
     * @todo   Implement testGetCalculation().
     */
    public function testGetCalculation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::setFirstInventory
     * @todo   Implement testSetFirstInventory().
     */
    public function testSetFirstInventory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::getFirstInventory
     * @todo   Implement testGetFirstInventory().
     */
    public function testGetFirstInventory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::setCurrency
     * @todo   Implement testSetCurrency().
     */
    public function testSetCurrency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Settings::getCurrency
     * @todo   Implement testGetCurrency().
     */
    public function testGetCurrency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
