<?php

namespace AppBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:38.
 */
class SubFamilyLogTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SubFamilyLog
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SubFamilyLog;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::addFamilylog
     * @todo   Implement testAddFamilylog().
     */
    public function testAddFamilylog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::removeFamilylog
     * @todo   Implement testRemoveFamilylog().
     */
    public function testRemoveFamilylog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::getFamilylogs
     * @todo   Implement testGetFamilylogs().
     */
    public function testGetFamilylogs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::setFamilylog
     * @todo   Implement testSetFamilylog().
     */
    public function testSetFamilylog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::getFamilylog
     * @todo   Implement testGetFamilylog().
     */
    public function testGetFamilylog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::jsonSerialize
     * @todo   Implement testJsonSerialize().
     */
    public function testJsonSerialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SubFamilyLog::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
