<?php

namespace AppBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:30.
 */
class SupplierRepositoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SupplierRepository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SupplierRepository;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\SupplierRepository::getSuppliers
     * @todo   Implement testGetSuppliers().
     */
    public function testGetSuppliers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\SupplierRepository::getSupplierForReassign
     * @todo   Implement testGetSupplierForReassign().
     */
    public function testGetSupplierForReassign() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
