<?php

namespace AppBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:36.
 */
class SupplierTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Supplier
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Supplier;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\Supplier::setDelaydeliv
     * @todo   Implement testSetDelaydeliv().
     */
    public function testSetDelaydeliv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::getDelaydeliv
     * @todo   Implement testGetDelaydeliv().
     */
    public function testGetDelaydeliv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::setOrderdate
     * @todo   Implement testSetOrderdate().
     */
    public function testSetOrderdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::getOrderdate
     * @todo   Implement testGetOrderdate().
     */
    public function testGetOrderdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::setFamilyLog
     * @todo   Implement testSetFamilyLog().
     */
    public function testSetFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::getFamilyLog
     * @todo   Implement testGetFamilyLog().
     */
    public function testGetFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::setSubFamilyLog
     * @todo   Implement testSetSubFamilyLog().
     */
    public function testSetSubFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::getSubFamilyLog
     * @todo   Implement testGetSubFamilyLog().
     */
    public function testGetSubFamilyLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::setSlug
     * @todo   Implement testSetSlug().
     */
    public function testSetSlug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::getSlug
     * @todo   Implement testGetSlug().
     */
    public function testGetSlug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::setActive
     * @todo   Implement testSetActive().
     */
    public function testSetActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\Supplier::isActive
     * @todo   Implement testIsActive().
     */
    public function testIsActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
