<?php

namespace AppBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:34.
 */
class UserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Entity\User::setLoginCount
     * @todo   Implement testSetLoginCount().
     */
    public function testSetLoginCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getLoginCount
     * @todo   Implement testGetLoginCount().
     */
    public function testGetLoginCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::setFirstLogin
     * @todo   Implement testSetFirstLogin().
     */
    public function testSetFirstLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getFirstLogin
     * @todo   Implement testGetFirstLogin().
     */
    public function testGetFirstLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getEnabled
     * @todo   Implement testGetEnabled().
     */
    public function testGetEnabled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getLocked
     * @todo   Implement testGetLocked().
     */
    public function testGetLocked() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getExpired
     * @todo   Implement testGetExpired().
     */
    public function testGetExpired() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getExpiresAt
     * @todo   Implement testGetExpiresAt().
     */
    public function testGetExpiresAt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getCredentialsExpired
     * @todo   Implement testGetCredentialsExpired().
     */
    public function testGetCredentialsExpired() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::getCredentialsExpireAt
     * @todo   Implement testGetCredentialsExpireAt().
     */
    public function testGetCredentialsExpireAt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::setSalt
     * @todo   Implement testSetSalt().
     */
    public function testSetSalt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::setGroups
     * @todo   Implement testSetGroups().
     */
    public function testSetGroups() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::setRoles
     * @todo   Implement testSetRoles().
     */
    public function testSetRoles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Entity\User::hasGroup
     * @todo   Implement testHasGroup().
     */
    public function testHasGroup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
