<?php

namespace Glsr\GestockBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-03-12 at 16:31:58.
 */
class GestockControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GestockController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GestockController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Glsr\GestockBundle\Controller\GestockController::indexAction
     *
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\GestockController::fillSubFamilyLogAction
     *
     * @todo   Implement testFillSubFamilyLogAction().
     */
    public function testFillSubFamilyLogAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\GestockController::getFamilyLogAction
     *
     * @todo   Implement testGetFamilyLogAction().
     */
    public function testGetFamilyLogAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\GestockController::alertsAction
     *
     * @todo   Implement testAlertsAction().
     */
    public function testAlertsAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
