<?php

namespace Glsr\GestockBundle\Tests\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-03-12 at 16:31:57.
 */
class InventoryControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var InventoryController
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new InventoryController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Glsr\GestockBundle\Controller\InventoryController::indexAction
     *
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\InventoryController::prepareAction
     *
     * @todo   Implement testPrepareAction().
     */
    public function testPrepareAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers Glsr\GestockBundle\Controller\InventoryController::cancelAction
     *
     * @todo   Implement testCancelAction().
     */
    public function testCancelAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\InventoryController::entryAction
     *
     * @todo   Implement testEntryAction().
     */
    public function testEntryAction()
    {
        $inventory = new \Glsr\GestockBundle\Entity\Inventory();
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\
     *   InventoryController::differencesStockAction
     *
     * @todo   Implement testDifferencesStockAction().
     */
    public function testDifferencesStockAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\InventoryController::validAction
     *
     * @todo   Implement testValidAction().
     */
    public function testValidAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
