<?php

namespace Glsr\GestockBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-03-12 at 16:31:56.
 */
class SettingsControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SettingsController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SettingsController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::showCompanyAction
     *
     * @todo   Implement testShowCompanyAction().
     */
    public function testShowCompanyAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::showApplicationAction
     *
     * @todo   Implement testShowApplicationAction().
     */
    public function testShowApplicationAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::showDiversAction
     *
     * @todo   Implement testShowDiversAction().
     */
    public function testShowDiversAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::addSettingsAction
     *
     * @todo   Implement testAddSettingsAction().
     */
    public function testAddSettingsAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::editSettingsAction
     *
     * @todo   Implement testEditSettingsAction().
     */
    public function testEditSettingsAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::addCompanyAction
     *
     * @todo   Implement testAddCompanyAction().
     */
    public function testAddCompanyAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::editCompanyAction
     *
     * @todo   Implement testEditCompanyAction().
     */
    public function testEditCompanyAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::addFamilyLogAction
     *
     * @todo   Implement testAddFamilyLogAction().
     */
    public function testAddFamilyLogAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::editFamilyLogAction
     *
     * @todo   Implement testEditFamilyLogAction().
     */
    public function testEditFamilyLogAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::addSubFamilyLogAction
     *
     * @todo   Implement testAddSubFamilyLogAction().
     */
    public function testAddSubFamilyLogAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::editSubFamilyLogAction
     *
     * @todo   Implement testEditSubFamilyLogAction().
     */
    public function testEditSubFamilyLogAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::addZoneStorageAction
     *
     * @todo   Implement testAddZoneStorageAction().
     */
    public function testAddZoneStorageAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::editZoneStorageAction
     *
     * @todo   Implement testEditZoneStorageAction().
     */
    public function testEditZoneStorageAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::addUnitStorageAction
     *
     * @todo   Implement testAddUnitStorageAction().
     */
    public function testAddUnitStorageAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::editUnitStorageAction
     *
     * @todo   Implement testEditUnitStorageAction().
     */
    public function testEditUnitStorageAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::addTvaAction
     *
     * @todo   Implement testAddTvaAction().
     */
    public function testAddTvaAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SettingsController::editTvaAction
     *
     * @todo   Implement testEditTvaAction().
     */
    public function testEditTvaAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
