<?php

namespace Glsr\GestockBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-03-12 at 16:31:57.
 */
class SupplierControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SupplierController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SupplierController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SupplierController::indexAction
     *
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SupplierController::addAction
     *
     * @todo   Implement testAddAction().
     */
    public function testAddAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SupplierController::editAction
     *
     * @todo   Implement testEditAction().
     */
    public function testEditAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SupplierController::deleteAction
     *
     * @todo   Implement testDeleteAction().
     */
    public function testDeleteAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Glsr\GestockBundle\Controller\SupplierController::showAction
     *
     * @todo   Implement testShowAction().
     */
    public function testShowAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
