## EASY_ADMIN Menu template.
---
easy_admin:
    design:
        menu:
            - { label: 'menu.staff' }
            - { entity: 'User', icon: 'user' }
            - label: 'menu.settings'
              icon: 'cogs'
              children:
                - { entity: 'Company', icon: 'building' }
                - { entity: 'Settings', icon: 'cog' }
                - { label: 'menu.diverse', icon: 'info-circle' }
                - { entity: 'FamilyLog', icon: 'sitemap' }
                #, params: { sortField: 'parent', sortDirection: 'ASC' } }
            - { label: 'Env: %env(APP_ENV)%' }
