## EASY_ADMIN Menu template.
---
easy_admin:
    design:
        menu:
            - { label: 'menu.staff' }
            - { entity: 'User', icon: 'user' }
            - { label: 'menu.settings' }
            - { entity: 'Company', icon: 'building' }
            - { entity: 'Settings', icon: 'cog' }
            - { label: 'menu.diverse', icon: 'info-circle' }
            - { entity: 'FamilyLog', icon: 'sitemap' }
            - { entity: 'Unit', icon: 'cubes' }
            - { entity: 'ZoneStorage', icon: 'map-marker', sortField: 'id', sortDirection: 'ASC' }
            - { entity: 'Tva', icon: 'percent' }
            - { label: 'Env: %env(APP_ENV)%' }
