admin:
  resource: routes/administration/index.yaml
  prefix: /administration

inventory:
  resource: routes/inventory/index.yaml
  prefix: /inventory

_home:
  path: /
  controller: Core\Infrastructure\Controller\DefaultController
  methods: GET
