services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Behat\DemoContext:
        public: true
        arguments:
            - "@kernel"

    Tests\Behat\:
        resource: '../tests/Behat/*'
