# src/Glsr/GestockBundle/Resources/config/routing.yml

glstock_home:
    path:  /
    defaults: { _controller: GlsrGestockBundle:Gestock:index }
    requirements:
        _method:  GET

# Routes Company
glstock_company_show:
    path:  settings/company
    defaults: { _controller: GlsrGestockBundle:Settings/Company:show }
    requirements:
        _method:  GET
glstock_company_add:
    path:  /company/add
    defaults: { _controller: GlsrGestockBundle:Settings/Company:addShow }
    requirements:
        _method:  GET
glstock_company_add_process:
    path:  /company/add
    defaults: { _controller: GlsrGestockBundle:Settings/Company:addProcess }
    requirements:
        _method:  POST
glstock_company_edit:
    path:  /company/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Company:editShow }
    requirements:
        id: \d+
        _method:  GET
glstock_company_edit_process:
    path:  /company/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Company:editProcess }
    requirements:
        id: \d+
        _method:  POST

# Routes Application
glstock_application_show:
    path:  settings/application
    defaults: { _controller: GlsrGestockBundle:Settings/Application:show }
    requirements:
        _method:  GET
glstock_application_add:
    path:  /application/add
    defaults: { _controller: GlsrGestockBundle:Settings/Application:addShow }
    requirements:
        _method:  GET
glstock_application_add_process:
    path:  /application/add
    defaults: { _controller: GlsrGestockBundle:Settings/Application:addProcess }
    requirements:
        _method:  POST
glstock_application_edit:
    path:  /settings/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Application:editShow }
    requirements:
        id: \d+
        _method:  GET
glstock_application_edit_process:
    path:  /settings/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Application:editProcess }
    requirements:
        id: \d+
        _method:  POST

glstock_divers:
    path:  settings/divers
    defaults: { _controller: GlsrGestockBundle:Settings/Divers:show }
    requirements:
        _method:  GET
        
glstock_setdiv_famlog_add:
    path:  /familylog/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/FamilyLog:addShow }
    requirements:
        _method:  GET
glstock_setdiv_famlog_add_process:
    path:  /familylog/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/FamilyLog:addProcess }
    requirements:
        _method:  POST
glstock_setdiv_famlog_edit:
    path:  /familylog/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/FamilyLog:editShow }
    requirements:
        id: \d+
        _method:  GET
glstock_setdiv_famlog_edit_process:
    path:  /familylog/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/FamilyLog:editProcess }
    requirements:
        id: \d+
        _method:  POST

glstock_setdiv_subfamlog_add:
    path:  /subfamilylog/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/SubFamilyLog:addShow }
    requirements:
        _method:  GET
glstock_setdiv_subfamlog_add_process:
    path:  /subfamilylog/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/SubFamilyLog:addProcess }
    requirements:
        _method:  POST
glstock_setdiv_subfamlog_edit:
    path:  /subfamilylog/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/SubFamilyLog:editShow }
    requirements:
        id: \d+
        _method:  GET
glstock_setdiv_subfamlog_edit_process:
    path:  /subfamilylog/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/SubFamilyLog:editProcess }
    requirements:
        id: \d+
        _method:  POST

glstock_setdiv_zonestorage_add:
    path:  /zonestorage/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/ZoneStorage:addShow }
    requirements:
        _method:  GET
glstock_setdiv_zonestorage_add_process:
    path:  /zonestorage/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/ZoneStorage:addProcess }
    requirements:
        _method:  POST
glstock_setdiv_zonestorage_edit:
    path:  /zonestorage/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/ZoneStorage:editShow }
    requirements:
        id: \d+
        _method:  GET
glstock_setdiv_zonestorage_edit_process:
    path:  /zonestorage/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/ZoneStorage:editProcess }
    requirements:
        id: \d+
        _method:  POST

glstock_setdiv_unitstorage_add:
    path:  /unitstorage/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/UnitStorage:addShow }
    requirements:
        _method:  GET
glstock_setdiv_unitstorage_add_process:
    path:  /unitstorage/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/UnitStorage:addProcess }
    requirements:
        _method:  POST
glstock_setdiv_unitstorage_edit:
    path:  /unitstorage/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/UnitStorage:editShow }
    requirements:
        id: \d+
        _method:  GET
glstock_setdiv_unitstorage_edit_process:
    path:  /unitstorage/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/UnitStorage:editProcess }
    requirements:
        id: \d+
        _method:  POST

glstock_setdiv_tva_add:
    path:  /tva/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/Tva:addShow }
    requirements:
        _method:  GET
glstock_setdiv_tva_add_process:
    path:  /tva/add
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/Tva:addProcess }
    requirements:
        _method:  POST
glstock_setdiv_tva_edit:
    path:  /tva/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/Tva:editShow }
    requirements:
        id: \d+
        _method:  GET
glstock_setdiv_tva_edit_process:
    path:  /tva/edit/{id}
    defaults: { _controller: GlsrGestockBundle:Settings/Divers/Tva:editProcess }
    requirements:
        id: \d+
        _method:  POST

# Routes des Articles
glstock_art_add:
    path:  /article/add
    defaults: { _controller: GlsrGestockBundle:Article:addShow }
    requirements:
        _method:  GET
glstock_art_add_process:
    path:  /article/add
    defaults: { _controller: GlsrGestockBundle:Article:addProcess }
    requirements:
        _method:  POST
glstock_art_edit:
    path:  /article/edit/{name}
    defaults: { _controller: GlsrGestockBundle:Article:editShow }
    requirements:
        _method:  GET
glstock_art_edit_process:
    path:  /article/edit/{name}
    defaults: { _controller: GlsrGestockBundle:Article:editProcess }
    requirements:
        _method:  POST
glstock_art_del:
    path:  /article/delete/{id}
    defaults: { _controller: GlsrGestockBundle:Article:deleteShow }
    requirements:
        id:      \d+
        _method: GET
glstock_art_del_process:
    path:  /article/delete/{id}
    defaults: { _controller: GlsrGestockBundle:Article:deleteProcess }
    requirements:
        id:      \d+
        _method: POST
glstock_art_list:
    path:  /article/{page}
    defaults: { _controller: GlsrGestockBundle:Article:index, page: 1 }
    requirements:
        page:  \d+
glstock_art_show:
    path:  /article/{name}
    defaults: { _controller: GlsrGestockBundle:Article:show }
glstock_reassign_article:
    path:  /article/reassign/{id}
    defaults: { _controller: GlsrGestockBundle:Article:reassignShow }
    requirements:
        id:      \d+
        _method: GET
glstock_reassign_article_process:
    path:  /article/reassign/{id}
    defaults: { _controller: GlsrGestockBundle:Article:reassignProcess }
    requirements:
        id:      \d+
        _method: POST

# Routes des Suppliers
glstock_suppli_add:
    path:  /supplier/add
    defaults: { _controller: GlsrGestockBundle:Supplier:addShow }
    requirements:
        _method:  GET
glstock_suppli_add_process:
    path:  /supplier/add
    defaults: { _controller: GlsrGestockBundle:Supplier:addProcess }
    requirements:
        _method:  POST
glstock_suppli_edit:
    path:  /supplier/edit/{name}
    defaults: { _controller: GlsrGestockBundle:Supplier:editShow }
    requirements:
        _method:  GET
glstock_suppli_edit_process:
    path:  /supplier/edit/{name}
    defaults: { _controller: GlsrGestockBundle:Supplier:editProcess }
    requirements:
        _method:  POST
glstock_suppli_del:
    path:  /supplier/delete/{id}
    defaults: { _controller: GlsrGestockBundle:Supplier:deleteShow }
    
    requirements:
        id:       \d+
        _method: GET
glstock_suppli_del_process:
    path:  /supplier/delete/{id}
    defaults: { _controller: GlsrGestockBundle:Supplier:deleteProcess }
    requirements:
        id:       \d+
        _method: POST
glstock_suppli_list:
    path:  /supplier/{page}
    defaults: { _controller: GlsrGestockBundle:Supplier:index, page: 1 }
    requirements:
        page:  \d+
glstock_suppli_show:
    path:  /supplier/{name}
    defaults: { _controller: GlsrGestockBundle:Supplier:show }

# route des alertes
glstock_show:
    path:  /
    defaults: { _controller: GlsrGestockBundle:Gestock:index }

# route selects liés
fill_subfamilylog:
    path:  /fill_subfamilylog
    defaults: { _controller: GlsrGestockBundle:Gestock:fillSubFamilyLog }
    requirements:
        _method: POST
getfamilylog:
    path:  /getfamilylog
    defaults: { _controller: GlsrGestockBundle:Gestock:getFamilyLog }
    requirements:
        _method: POST

# route Inventory
glstock_inventory:
    path:  /inventory
    defaults: { _controller: GlsrGestockBundle:Inventory:index }
glstock_inventory_prepare:
    path:  /inventory/prepare
    defaults: { _controller: GlsrGestockBundle:Inventory:prepare }
glstock_inventory_cancel:
    path:  /inventory/cancel/{id}
    defaults: { _controller: GlsrGestockBundle:Inventory:cancel }
    requirements:
        id:      \d+
glstock_inventory_entry:
    path:     /inventory/entry/{id}
    defaults: { _controller: GlsrGestockBundle:Inventory:entryShow }
    requirements:
        id:      \d+
        _method: GET
glstock_inventory_entry_process:
    path:      /inventory/entry/{id}
    defaults:  { _controller: GlsrGestockBundle:Inventory:entryProcess }
    requirements:
        id:    \d+
        _method: POST
glstock_inventory_valid:
    path:  /inventory/valid
    defaults: { _controller: GlsrGestockBundle:Inventory:valid }
    requirements:
        id:  \d+
