# J'ai sorti cette route afin de ne pas avoir le préfixe /gestock lors de l'import
glsrgestock_home:
    path:   /
    defaults:  { _controller: GlsrGestockBundle:Gestock:index }
    requirements:
        methods:  GET
