parameters:
#    glsr_user.example.class: Sdz\UserBundle\Example

services:
#    glsr_user.example:
#        class= %glsr_user.example.class%
#            arguments: [@service_id, "plain_value", %parameter_name%]
