<?php

namespace AppBundle\Form\Type;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:16.
 */
class GroupTypeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var GroupType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GroupType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Form\Type\GroupType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Form\Type\GroupType::configureOptions
     * @todo   Implement testConfigureOptions().
     */
    public function testConfigureOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Form\Type\GroupType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
