<?php

namespace AppBundle\Form\Type;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:15.
 */
class UserTypeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UserType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UserType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Form\Type\UserType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Form\Type\UserType::configureOptions
     * @todo   Implement testConfigureOptions().
     */
    public function testConfigureOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Form\Type\UserType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
