<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryRepository extends EntityRepository
{
    /**
     * Affiche les inventaires actifs.
     *
     * @return QueryBuilder Requête DQL
     */
    public function getInventory()
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.status > 0')
            ->orderBy('i.id', 'DESC')
            ->getQuery();
        
        return $query->getResult();
    }

    /**
     * Renvoi les derniers inventaires.
     *
     * @param integer $count Nombre d'élément à afficher
     * @return array Query result
     */
    public function getLastInventory($count)
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.status > 0')
            ->orderBy('i.id', 'DESC')
            ->setMaxResults($count)
            ->getQuery();

        return $query->getResult();
    }
}
