<?php

namespace AppBundle\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:21.
 */
class RegistrationControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RegistrationController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RegistrationController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Controller\RegistrationController::registerAction
     * @todo   Implement testRegisterAction().
     */
    public function testRegisterAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Controller\RegistrationController::confirmedAction
     * @todo   Implement testConfirmedAction().
     */
    public function testConfirmedAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
