@startuml
left to right direction
skinparam packageStyle rectangle
actor Admin
database "Database \nEntity \nStorage" as Database

rectangle "Administration" {
	Admin -- (Log in)
	Admin -- [Create a\nuser]
	(Log in) -- Database
	[Create a\nuser] -- Database
	Admin -- [Configure\nSettings]
	Admin -- [Configure\nSupplier]
	Admin -- [Configure\nArticle]
	[Configure\nSupplier] -- Database
	[Configure\nArticle] -- Database
	[Configure\nSettings] -- Database
}

@enduml
