@startuml
left to right direction
skinparam packageStyle rectangle

rectangle "Inventory" {
	usecase "1. Log in" as uc1
	usecase "2. Prepare inventory" as uc2
	usecase "3. Enters inventory" as uc3
	usecase "4. Compare and correct" as uc4
	usecase "5. Valid inventory" as uc5
}

actor User
database "Database \nEntity \nStorage" as Database
database "Elastic \nSearch \nStorage" as DTOStorage

	User -- (uc1)
	(uc1) -- Database
	User -- (uc2)
	note right of (uc2) : "Inventory is printed"
	(uc2) -- DTOStorage
	User -- (uc3)
	User -- (uc4)
	User -- (uc5)
	(uc5) -- Database

@enduml
