@startuml
left to right direction
skinparam packageStyle rectangle

actor Admin
database "Database \nEntity \nStorage" as Database

rectangle "Settings\n'Configuration'" {
	Admin -- (Configure Company)
	Admin -- (Configure FamilyLog)
	Admin -- (Configure ZoneStorage)
	Admin -- (Configure Unit)
	Admin -- (Configure Taxe)
	Admin -- (Configure Application)
	(Configure Company) -- Database
	(Configure FamilyLog) -- Database
	(Configure ZoneStorage) -- Database
	(Configure Unit) -- Database
	(Configure Taxe) -- Database
	(Configure Application) -- Database
}

@enduml
