## EASY_ADMIN Article Entity
---
easy_admin:
    entities:
        Article:
            class: App\Entity\Settings\Article
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Name' }
                    - supplier
                    - { property: 'familylog', sortable: true }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'form.article.info', icon: 'info-circle ' }
                    - { property: 'name', label: 'Name' }
                    - { property: 'supplier', type: 'entity', type_options: { class: 'App:Settings\Supplier', choice_label: 'name', multiple: false, placeholder: 'form.supplier.choice', attr: { onChange: 'getFamilyLog();' } }, label: 'supplier.name' }
                    - { type: 'divider' }
                    - { property: 'zoneStorages', type: 'entity', type_options: { class: 'App:Settings\Diverse\ZoneStorage', choice_label: 'name', multiple: true, expanded: true, placeholder: 'form.zoneStorage.choice' }, label: 'ZoneStorage' }
                    - { property: 'familylog', type: 'App\Form\Type\FamilyLogSelectType', type_options: { class: 'App:Settings\Diverse\FamilyLog', choice_label: 'indentedName', multiple: false, placeholder: 'form.familyLog.choice' }, label: 'FamilyLog' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'form.feature', icon: 'cog' }
                    - { property: 'packaging', type: 'number', type_options: { scale: 3, grouping: true }, label: 'article.settings.packaging' }
                    - { property: 'unitStorage', type: 'entity', type_options: { class: 'App:Settings\Diverse\Unit', choice_label: 'name', multiple: false, placeholder: 'form.unitStorage.choice' }, label: 'UnitStorage' }
                    - { property: 'price', type: 'money', type_options: { scale: 3, grouping: true, currency: 'EUR' }, label: 'article.settings.price' }
                    - { property: 'tva', type: 'entity', type_options: { class: 'App:Settings\Diverse\Tva', choice_label: 'name', multiple: false, placeholder: 'form.tva.choice' }, label: 'tva.rate' }
                    - { type: 'divider' }
                    - { property: 'unitWorking', type: 'entity', type_options: { class: 'App:Settings\Diverse\Unit', choice_label: 'name', multiple: false, placeholder: 'form.unitWorking.choice' }, label: 'article.settings.unitWorking' }
                    - { property: 'minstock', type: 'number', type_options: { scale: 3, grouping: true }, label: 'article.settings.minstock' }
            edit:
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: 'form.article.complement', icon: 'file' }
                    - { property: 'createAt', type: 'date', label: 'article.settings.createAt' }
                    - { property: 'updateAt', type: 'date', label: 'article.settings.updateAt' }
                    - { property: 'deleteAt', type: 'date', label: 'article.settings.deleteAt' }
            show:
                fields:
                    - id
                    - { property: 'name', label: 'Name' }
                    - supplier
                    - familylog
                    - zoneStorages
                    - { property: 'packaging', label: 'article.settings.packaging' }
                    - { property: 'unitStorage', label: 'UnitStorage' }
                    - { property: 'price', type: 'decimal', label: 'article.settings.price' }
                    - { property: 'tva', label: 'tva.rate' }
                    - { property: 'unitWorking', label: 'article.settings.unitWorking' }
                    - { property: 'minstock', label: 'article.settings.minstock' }
                    - { property: 'createAt', type: 'date', label: 'article.settings.createAt' }
                    - { property: 'updateAt', type: 'date', label: 'article.settings.updateAt' }
                    - { property: 'deleteAt', type: 'date', label: 'article.settings.deleteAt' }
