## EASY_ADMIN Supplier Entity
---
easy_admin:
    entities:
        Supplier:
            class: App\Entity\Settings\Supplier
            controller: App\Controller\SupplierController
            permissions:
                new: ['ROLE_SUPER_ADMIN']
                edit: ['ROLE_SUPER_ADMIN']
                delete: ['ROLE_SUPER_ADMIN']
            list:
                dql_filter: 'entity.active = 1'
                fields:
                    - name
                    - { property: 'completeAddress', type: 'raw', label: 'Address', sortable: false }
                    - { property: 'phone', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'admin/field_tel.html.twig', sortable: false }
                    - { property: 'contact', sortable: false }
                    - { property: 'email', type: 'email', sortable: false }
                    - { property: 'familylog', sortable: true, label: 'FamilyLog' }

            form:
                fields:
                    - { type: 'group', columns: 12, label: 'Basics informations', icon: 'building' }
                    - { property: 'name', label: 'supplier.name' }
                    - { property: 'address', columns: 6 }
                    - { property: 'phone', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', columns: 6, type_options: { widget: 'country_choice', country_choices: [ 'GB', 'DE', 'FR' ], preferred_country_choices: [ 'FR' ], block_name: 'custom_tel' } }
                    - { property: 'zipcode', columns: 2 }
                    - { property: 'town', columns: 4, type_options: { attr: { 'onBlur': 'this.value.toUpperCase()', 'onFocus': 'this.value.toUpperCase()', 'onKeyup': 'this.value.toUpperCase()' } } }
                    - { property: 'fax', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', columns: 6, type_options: { widget: 'country_choice', country_choices: [ 'GB', 'DE', 'FR' ], preferred_country_choices: [ 'FR' ], block_name: 'custom_tel' } }
                    - { type: 'group', columns: 6, label: 'Contact informations', icon: 'phone' }
                    - { property: 'contact', columns: 6 }
                    - { property: 'gsm', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', columns: 6, type_options: { widget: 'country_choice', country_choices: [ 'GB', 'DE', 'FR' ], preferred_country_choices: [ 'FR' ], block_name: 'custom_tel' } }
                    - { property: 'email', type: 'email', columns: 12 }
                    - { type: 'group', columns: 6, label: 'Logistics Informations', icon: 'truck' }
                    - { property: 'familylog', type: 'App\Form\Type\FamilyLogSelectType', columns: 6, type_options: { class: 'App\Entity\Settings\Diverse\FamilyLog', choice_label: 'indentedName', multiple: false, attr: { data-widget: 'select2' } }, label: 'FamilyLog' }
                    # Delivery Time: A = Order Day to (B, C, D, E) = delivery day
                    - { property: 'delaydeliv', type: 'choice', columns: 6, type_options: { choices: { 'AtoB': 1,'AtoC': 2,'AtoD': 3,'AtoE': 4 }, expanded: false, multiple: false, attr: { data-widget: 'select2' } }, label: 'supplier.delayliv' }
                    # Choice of the day of the week for Orders
                    # Numbering see: http://php.net/manual/fr/function.date.php format 'N'
                    - { property: 'orderdate', type: 'choice', type_options: { choices: { 'Monday': 1,'Tuesday': 2,'Wednesday': 3,'Thursday': 4,'Friday': 5,'Saturday': 6,'Sunday': 7 }, expanded: true, multiple: true, label_attr: { class: 'checkbox-inline' } }, label: 'supplier.orderday' }
            show:
                fields:
                    - { property: 'name', label: 'supplier.name' }
                    - { property: 'completeAddress', type: 'raw', label: 'Address' }
                    - { property: 'contact' }
                    - { property: 'email', type: email }
                    - { property: 'phone', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'admin/field_tel.html.twig' }
                    - { property: 'fax', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'admin/field_tel.html.twig' }
                    - { property: 'gsm', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'admin/field_tel.html.twig' }
                    - { property: 'familylog', type: string, label: 'FamilyLog' }
                    - { property: 'delaydeliv', label: 'supplier.delayliv' }
                    - { property: 'orderdate', label: 'supplier.orderday', template: 'admin/Supplier/field_simple_array.html.twig' }
                    - { property: 'articles', type: 'association', label: 'Article', template: '@EasyAdmin/default/field_association.html.twig' }
