## EASY_ADMIN Supplier Entity
---
easy_admin:
    entities:
        Supplier:
            class: App\Entity\Settings\Supplier
            controller: App\Controller\SupplierController
            list:
                dql_filter: 'entity.active = 1'
                fields:
                    - name
                    - { property: 'completeAddress', type: 'raw', label: 'Address', sortable: false }
                    - { property: 'phone', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'easy_admin/field_tel.html.twig', sortable: false }
                    - { property: 'contact', sortable: false }
                    - { property: 'email', type: 'email', sortable: false }
                    - { property: 'familylog', sortable: true, label: 'FamilyLog' }

            form:
                fields:
                    - { type: 'group', columns: 12, label: 'Basics information', icon: 'building' }
                    - { property: 'name', label: 'supplier.name' }
                    - address
                    - zipcode
                    - { property: town }
                    - { type: 'group', columns: 6, label: 'Contact information', icon: 'phone' }
                    - contact
                    - { property: 'email', type: 'email' }
                    - { property: 'phone', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', type_options: { widget: 'country_choice', country_choices: [ 'FR','GB','DE' ] }, preferred_choices: 'FR' }
                    - { property: 'fax', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', type_options: { widget: 'country_choice', country_choices: [ 'FR','GB','DE' ] }, preferred_choices: 'FR' }
                    - { property: 'gsm', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', type_options: { widget: 'country_choice', country_choices: [ 'FR','GB','DE' ] }, preferred_choices: 'FR' }
                    - { type: 'group', columns: 6, label: 'Logistics Information', icon: 'truck' }
                    - { property: 'familylog', type: 'App\Form\Type\FamilyLogSelectType', type_options: { class: 'App:Settings\Diverse\FamilyLog', choice_label: 'indentedName', multiple: false, attr: { data-widget: 'select2' } }, label: 'FamilyLog' }
                    # Delivery Time: A = Order Day to (B, C, D, E) = delivery day
                    - { property: 'delaydeliv', type: 'choice', type_options: { choices: { 'AtoB': 1,'AtoC': 2,'AtoD': 3,'AtoE': 4 }, expanded: false, multiple: false, attr: { data-widget: 'select2' } }, label: 'supplier.delayliv' }
                    # Choice of the day of the week for Orders
                    # Numbering see: http://php.net/manual/fr/function.date.php format 'N'
                    - { property: 'orderdate', type: 'choice', type_options: { choices: { 'Monday': 1,'Tuesday': 2,'Wednesday': 3,'Thursday': 4,'Friday': 5,'Saturday': 6,'Sunday': 7 }, expanded: true, multiple: true }, block_name: 'supplier_choice', label: 'supplier.orderday' }

            show:
                fields:
                    - { property: 'name', label: 'supplier.name' }
                    - { property: 'completeAddress', type: 'raw', label: 'Address' }
                    - { property: 'contact' }
                    - { property: 'email', type: email }
                    - { property: 'phone', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'easy_admin/field_tel.html.twig' }
                    - { property: 'fax', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'easy_admin/field_tel.html.twig' }
                    - { property: 'gsm', type: 'Misd\PhoneNumberBundle\Form\Type\PhoneNumberType', template: 'easy_admin/field_tel.html.twig' }
                    - { property: 'familylog', label: 'FamilyLog' }
                    - { property: 'delaydeliv', label: 'supplier.delayliv' }
                    - { property: 'orderdate', label: 'supplier.orderday', template: 'easy_admin/Supplier/field_simple_array.html.twig' }
