easy_admin:
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            permissions:
                new: ['ROLE_SUPER_ADMIN']
                edit: ['ROLE_SUPER_ADMIN']
                delete: ['ROLE_SUPER_ADMIN']
            label: Utilisateurs
            form:
                fields:
                    - { property: 'username', icon: 'user' }
                    - { property: 'password', type: 'password' }
                    - { property: 'confirmPassword', type: 'password', type_options: { required: true } }
                    - { property: 'assistant' }
                    - { property: 'admin' }
                    - enabled
            list:
                title: 'Les derniers utilisateurs'
                fields:
                    - { property: 'id' }
                    - { property: 'username', icon: 'user' }
                    - { property: 'roles' }
            show:
                fields: ['username', 'roles', 'enabled', 'admin', 'assistant']
            search: ~
