## EASY_ADMIN User Entity.
---
easy_admin:
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            form:
                fields: 
                    - username
                    - password
                    - email
                    - enabled
