## EASY_ADMIN User Entity.
---
easy_admin:
    entities:
        User:
            class: App\Entity\Staff\User
            controller: App\Controller\UserController
            list:
                fields:
                    - username
                    - { property: 'email', sortable: false }
                    - lastLogin
                    - enabled
                    
            form:
                fields: 
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, label: 'password' }
            edit:
                fields:
                    - { property: 'plainPassword', type_options: { required: false} }
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true} }
                form_options: { validation_groups: ['Registration'] }
            show:
                fields:
                    - username
                    - email
                    - lastLogin
