easy_admin:
    entities:
    #        # List the entity class name you want to manage
    #        - App\Entity\Product
    #        - App\Entity\Category
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            label: Utilisateurs
            form:
                fields:
                    - { property: 'username', icon: 'user' }
                    - { property: 'password', type: 'password' }
                    - { property: 'isAssistant' }
                    - { property: 'isAdmin' }
                    - enabled
            list:
                title: 'Les derniers utilisateurs'
                fields:
                    - { property: 'id' }
                    - { property: 'username', icon: 'user' }
                    - { property: 'roles' }
            show: ~
            search: ~
