<?php

namespace AppBundle\Listener;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-15 at 17:17:24.
 */
class LoginListenerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var LoginListener
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoginListener;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppBundle\Listener\LoginListener::getSubscribedEvents
     * @todo   Implement testGetSubscribedEvents().
     */
    public function testGetSubscribedEvents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Listener\LoginListener::onImplicitLogin
     * @todo   Implement testOnImplicitLogin().
     */
    public function testOnImplicitLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\Listener\LoginListener::onSecurityInteractiveLogin
     * @todo   Implement testOnSecurityInteractiveLogin().
     */
    public function testOnSecurityInteractiveLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
